//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compact()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int RID { get; set; }
        public int HID { get; set; }
        public Nullable<System.DateTime> Signed_Date { get; set; }
        public Nullable<int> Work_Time { get; set; }
        public int ServiceID { get; set; }
        public decimal Total_Price { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Status { get; set; }
        public int CID { get; set; }
    
        public virtual Housekeeper Housekeeper { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
