//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> ChatDate { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ChatId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ChatRoom ChatRoom { get; set; }
    }
}
