//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepliComment
    {
        public int Id { get; set; }
        public Nullable<int> HID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Housekeeper Housekeeper { get; set; }
    }
}
